### ISSUE TITLE
Support in place upgrade in Terraform

### ISSUE THREAD

**Issue by nhuisman-amz** [terraform-aws-modules/terraform-aws-managed-service-grafana#38] opened 2024-09-20 19:17 UTC
## Is your request related to a new offering from AWS?
Is this functionality available in the [AWS provider for Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs)? See [CHANGELOG.md](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md), too.
  - Yes ✅:  AWS Grafana V9.4 added in place upgrade support
  
## Is your request related to a problem? Please describe.
When using Terraform to upgrade from Grafana 9.x to 10.x customers reported that it created a new workspace along with new grafana workspace url instead of performing an in place upgrade.   Customers expect upgrades to be in place due to the friction caused by the workspace domain changing as well as the work required to migrate dashboards between workspaces.

## Describe the solution you'd like.
Support in place upgrades

## Describe alternatives you've considered.
None

## Additional context
None

**Comment by bryantbiggs** [comment] 2024-09-20 19:27
closing due to lack of reproduction

**Closed by bryantbiggs** 2024-09-20 19:27 UTC
